/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class biz_pi_KeyBoard */

#ifndef _Included_biz_pi_KeyBoard
#define _Included_biz_pi_KeyBoard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     biz_pi_KeyBoard
 * Method:    open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_biz_pi_KeyBoard_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     biz_pi_KeyBoard
 * Method:    readline
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_biz_pi_KeyBoard_readline
  (JNIEnv *, jobject, jint);

/*
 * Class:     biz_pi_KeyBoard
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_biz_pi_KeyBoard_close
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
